### PR TITLE
make the bluescreen responsive \o/

### PR DESCRIPTION
**Pull request by unfokus**

### CODE REVIEW

**Comment by annikahannig** [comment]
Okay it's now responsive, but the design looks broken.

**Comment by unfokus** [comment]
What looks broken? Works on my machine(TM)

**Comment by annikahannig** [comment]
*sigh*

**Comment by annikahannig** [comment]
image

Menu too wide,
Content now creates scrollbars,

**Comment by unfokus** [comment]
wait a minute

**Pull request merged**
